### ISSUE TITLE
[IT] ing - logo do header leva para site em port

### ISSUE THREAD

**Issue by filipethomaz** [photonauta35/institutotim-header-footer#104]
O logo do header do site em inglês abre nova aba com o site em português. O logo do footer abre na mesma aba, mas também em português.

Os logos do header e do footer da versão em inglês devem levar para a home da versão em inglês, na mesma aba

**Comment by gusgustavo** [comment]
Arrumado! Por favor validar e fechar a issue.

**Comment by anatolezano** [comment]
No mobile isso ainda acontece.

**Comment by anatolezano** [comment]
Ok!
