### ISSUE TITLE
[IT] [mobile] Botão "enviar" sobreposto ao footer

### ISSUE THREAD

**Issue by filipethomaz** [photonauta35/institutotim-header-footer#105]
Na página CONTATO o botão "enviar" está por cima do footer

Vale também para a versão em inglês

**Comment by gusgustavo** [comment]
Olhei nas duas versões e está ok, havia sido arrumado. 
Envia um print da tela?

**Comment by filipethomaz** [comment]
Segue o print (vi no "inspect" e no meu celular pra ter certeza que estava acontecendo isso mesmo)

![screenshot_20170504-134014](https://cloud.githubusercontent.com/assets/26875679/25714842/c19f4610-30cf-11e7-84d1-4b741e656f5a.png)

**Comment by gusgustavo** [comment]
Ops, não havia visto a tag mobile. Vou arrumar.

**Comment by gusgustavo** [comment]
Oi, arrumado!

**Comment by photonauta35** [comment]
ok!
