### ISSUE TITLE
[IT] [mobile] Fotos com tamanhos diferentes

### ISSUE THREAD

**Issue by filipethomaz** [photonauta35/institutotim-header-footer#106]
Na página PROJETOS (Iniciativas>projetos) as fotos aparecem em tamanhos diferentes. Devemos deixar todas do mesmo tamanho. 

Vale também para a versão em inglês.

Exemplo:
![selecao_059](https://cloud.githubusercontent.com/assets/641411/25761892/d3a8a322-31b2-11e7-804c-0ee9ce3a0bb8.png)

**Comment by anatolezano** [comment]
Ok!
