### ISSUE TITLE
[IT] [mobile] Manual da marca - lugar do footer na página

### ISSUE THREAD

**Issue by filipethomaz** [photonauta35/institutotim-header-footer#107]
É mais uma dúvida do que um report... na página MANUAL DA MARCA o footer aparece no meio da página. O que é o usual nesses casos em que há pouco conteúdo? deixar o footer no final ou do jeito que está, logo quando acaba o conteúdo?

**Comment by gusgustavo** [comment]
Isso é porque o site não possui um tamanho mínimo.
Veja a issue e sua resolução aqui:
https://github.com/photonauta35/institutotim-header-footer/issues/24

**Comment by filipethomaz** [comment]
Entendido! valeu!
