### ISSUE TITLE
[IT] Subitens do item "Sobre" estão em caixa baixa

### ISSUE THREAD

**Issue by anatolezano** [photonauta35/institutotim-header-footer#110]
Ao contrário dos outros subitens dos menu do header, os subitens do item "Sobre" estão em caixa baixa. Qual é o padrão, @filipethomaz?

**Comment by anatolezano** [comment]
![image](https://cloud.githubusercontent.com/assets/25586548/25746460/f6c72074-3179-11e7-988a-82bea3edd77f.png)

**Comment by filipethomaz** [comment]
@gusgustavo Pode confirmar qual era o padrão antes das alterações?

**Comment by photonauta35** [comment]
O padrão era tudo em caixa alta no header. 

Os itens estão em inglês, mas não estão em Title Case. 

Relembrando: 
- Todos os menus dos headers devem estar em uppercase (todas as letras em **MAIÚSCULA**);
- Todos os sub-itens de menu devem também estar  em uppercase (todas as letras em **MAIÚSCULA**);
- Todos itens de cabeça dos footers devem estar em estar  em uppercase (todas as letras em **MAIÚSCULA**);
- Todos sub-itens dos footers devem estar em estar  **T**itle **C**ase (**P**rimeiras **L**etras **E**m **M**aiúscula e **D**emais **L**etras **E**m **M**inúscula **C**omo **N**essa **F**rase)

Exemplo de footer:
![selecao_058](https://cloud.githubusercontent.com/assets/641411/25761798/79e7912c-31b2-11e7-974f-cb8b51718fd9.png)

**Comment by anatolezano** [comment]
Ok!
