### ISSUE TITLE
[IT] A página de Mapas não está abrindo

### ISSUE THREAD

**Issue by anatolezano** [photonauta35/institutotim-header-footer#113]
https://institutotim.org.br/project/mapas-culturais/

(Não sei se há notícias ou clippings com esse problema porque não chequei uma por uma, mas das páginas da home essa é a única).

**Comment by anatolezano** [comment]
Acabei de ver uma matéria que não abre: https://institutotim.org.br/2017/02/06/inscricoes-para-bolsas-it-obmep-2017/

**Comment by photonauta35** [comment]
esse problema é relacionado ao cache das páginas... clicando naquele botão de limpar o cache do nginx resolve. Resolvido!
