### ISSUE TITLE
[IT] Tirar itens duplicados do footer do site em inglês

### ISSUE THREAD

**Issue by anatolezano** [photonauta35/institutotim-header-footer#114]
Não é necessário ter subitens no menu do footer do site em inglês, já que eles não existem na home. Tirar esses subitens, deixar apenas os itens em azul e colocar os links correspondentes em cada item.

**Comment by anatolezano** [comment]
![image](https://cloud.githubusercontent.com/assets/25586548/25747138/d84326d6-317c-11e7-8090-0f35d1f5cbb1.png)

**Comment by anatolezano** [comment]
Também é necessário corrigir esses itens. O certo é About, Projects, Solutions (e não Communications), e inverter a ordem da quarta coluna, colocando News acima de Contact us.

**Comment by gusgustavo** [comment]
Oi, fiz as modificações, veja se está certinho.

**Comment by photonauta35** [comment]
perfeito.

**Comment by anatolezano** [comment]
@gusgustavo você poderia, por favor, alinhar a altura da última coluna (News e Contact Us) com as demais? A diferença é pequena, mas tracei uma linha pra você perceber que essa coluna está mais alta.

![image](https://cloud.githubusercontent.com/assets/25586548/25902966/725d9f56-3571-11e7-912b-3f75217e4644.png)

**Comment by anatolezano** [comment]
![exemplo footer it eng](https://cloud.githubusercontent.com/assets/25586548/25903024/a18e65bc-3571-11e7-94c3-c6c7d3d7e390.jpg)
