### ISSUE TITLE
[IT] Layout Mobile

### ISSUE THREAD

**Issue by photonauta35** [photonauta35/institutotim-header-footer#115]
ATENÇÃO: antes de lidar com esses itens, consulte a issue #84 
ATENÇÃO 2:  Qualquer distância de tela menor do que 1024 px é considerado MOBILE para este site e deve atender a esse comportamento, conforme igual site http://www.tim.com.br

- [ ] Tamanho da fonte errado no header
![selecao_019](https://cloud.githubusercontent.com/assets/641411/25756296/a1553fb8-319c-11e7-9189-9e460d383a78.png)

![selecao_024](https://cloud.githubusercontent.com/assets/641411/25756173/277e4a2c-319c-11e7-9c51-ae510b6646c6.png)

- [ ] Hiperlink no logo do footer deve apontar para topo do site 
![selecao_020](https://cloud.githubusercontent.com/assets/641411/25755537/c0f73626-3199-11e7-8866-05814c8ffd56.png)

- [ ] Tamanho do footer em 400px (que deveria ser o mínimo) de tela está quebrado pois o banner acima está estourando a tela
![selecao_021](https://cloud.githubusercontent.com/assets/641411/25755636/1f5e3fc0-319a-11e7-860c-4c814f5d42bb.png)

**Comment by anatolezano** [comment]
Ok!
