### ISSUE TITLE
[IT][mobile] Footer não vai até o final

### ISSUE THREAD

**Issue by filipethomaz** [photonauta35/institutotim-header-footer#119]
O footer deixa um espaço em branco na lateral, não vai até o final da página

**Comment by filipethomaz** [comment]
![whatsapp image 2017-05-19 at 11 54 06](https://cloud.githubusercontent.com/assets/26875679/26253722/b854412a-3c8a-11e7-8f4c-db3a08b798c5.jpeg)

**Comment by anatolezano** [comment]
Ok!
