### ISSUE TITLE
[IT] A página "manual da marca" está "esprimida"

### ISSUE THREAD

**Issue by gusgustavo** [photonauta35/institutotim-header-footer#24]
A página [Manual da Marca](https://institutotim.org.br/manual-da-marca/) e páginas com pouco conteúdo necessitam de um tamanho fixo no container principal para não ficarem esprimidas. Como isso não está no escopo desse projeto, só estou deixando indicado.

**Comment by robertkapa** [comment]
ok! Vou deixar eu e o @antoniocastanheira responsáveis por isso.

**Comment by robertkapa** [comment]
@antoniocastanheira quando puder, dê uma olhada nisso.

**Comment by robertkapa** [comment]
@vitorkato precisamos colocar um min-height no conteiner principal deste site para que essa página não apareça quebrada: https://institutotim.org.br/manual-da-marca/

**Comment by vitor-kato** [comment]
Fixed
