### ISSUE TITLE
[ALL] As redes sociais são do Instituto TIM ou do projeto?

### ISSUE THREAD

**Issue by gusgustavo** [photonauta35/institutotim-header-footer#25]

**Comment by robertkapa** [comment]
A diretiva é que sejam todas do Instituto TIM em todos os sites. No entanto, não foram criadas ainda, a equipe de comunicação está trabalhando com as redes dos projetos quando há. No caso de TFC e AWC existem redes dos projetos.

**Comment by robertkapa** [comment]
@anatolezano O Instituto TIm nos orientou a usar redes sociais gerais, isto é, rede sociais do Instituto em detrimento das redes de cada projeto. No entanto sabemos que as redes sociais do Instituto ainda não existem, correto? 

Vc poderia nos indicar os links das redes sociais dos projetos? 

-[ ] Redes Sociais Instituto TIM

-[ ] Redes Sociais TIm Faz Ciência

-[ ] Redes Sociais TIM Tec

-[ ] Redes Sociais AWC

**Comment by anatolezano** [comment]
Exatamente, Felipe! A Carol disse que isso será alinhado com a Carol Meireles em março, até mesmo porque as duas estão de férias. Realmente, as redes sociais dos projetos devem cair, só não sabemos se todas ou apenas o Facebook (TFC, por exemplo, usa bastante o Flickr para divulgar as milhares de fotos enviadas pelos professores). De qualquer forma, seguem as redes:

- Redes sociais IT: tem um canal no YouTube, mas a Carol não sabe se será mantido ou se os vídeos serão incorporados ao canal da TIM Brasil
https://www.youtube.com/channel/UCgvBZ2qIQageqS2102hMHfw

- Redes sociais TFC:
https://www.facebook.com/timfazciencia
https://www.youtube.com/channel/UCWnd3qxdHRziiDG_yJfU1hQ
https://www.flickr.com/photos/121406068@N03/albums
https://www.flickr.com/photos/128197418@N02/albums

- Redes sociais TIM Tec:
https://www.facebook.com/TIMTecoficial/?fref=ts
https://twitter.com/TIMTec_oficial
https://github.com/institutotim/timtec (conta como rede? Incluí porque está no rodapé da página entre as redes sociais)

- Redes sociais AWC:
https://twitter.com/programaawc

**Comment by robertkapa** [comment]
@gusgustavo com base nessas redes, já é possível inserir os icones no header. Os ícones do site Instituto devem ser mantidos fora por hora. Mas o resto dos sites podemos colocar. Vale lembrar que o ícone contato (uma arroba ou um envelopinho do font-awesome) tem que ser posto em todos os site e deve redirecionar para a página de contato.

**Comment by photonauta35** [comment]
Decisão final sobre essa issue: nenhum header e footer deve conter links para redes sociais, conforme modelos: 

Header:

![selecao_050](https://cloud.githubusercontent.com/assets/641411/25758589/84d46eaa-31a5-11e7-8ea5-8ea68c7b93cc.png)

Footer:
![selecao_050](https://cloud.githubusercontent.com/assets/641411/25760667/34861abc-31ae-11e7-81cc-b350736d8cd4.png)
