### ISSUE TITLE
[IT] Rodapé: no site em inglês os itens devem estar em Inglês e title case

### ISSUE THREAD

**Issue by anatolezano** [photonauta35/institutotim-header-footer#32]
![selecao_120](https://cloud.githubusercontent.com/assets/641411/22654472/fbd679a2-ec73-11e6-9480-6511e8296112.png)

**Comment by gusgustavo** [comment]
Resolvido

**Comment by robertkapa** [comment]
Os itens estão em inglês, mas não estão em Title Case. 

Relembrando: 
- Todos os headers devem estar em uppercase (todas as letras em **MAIÚSCULA**);
- Todos os footers devem estar em **T**itle **C**ase (**P**rimeiras **L**etras **E**m **M**aiúscula e **D**emais **L**etras **E**m **M**inúscula **C**omo **N**essa **F**rase)

**Comment by anatolezano** [comment]
Gente, uma dúvida: para ficar padronizado com o português, não seria melhor trocar "get to know the Instituto TIM" por "About"? E o restante do rodapé ainda vai ser mudado para refletir o menu do header (assim como o português), certo?

**Comment by anatolezano** [comment]
Mais uma coisa: no rodapé do site em inglês, a frase: "Todos os direitos reservados" deve constar como "All rights reserved".

**Comment by robertkapa** [comment]
pendente: 

"All rights reserved" na versão inglês

**Comment by anatolezano** [comment]
Não falta só isso, aqui ainda está tudo desajustado. Além do fato de que "Get to know the Instituto TIM" deveria virar "About", não? Para ficar igual ao português.

**Comment by anatolezano** [comment]
Aqui também não foi corrigido.

**Comment by gusgustavo** [comment]
Arrumado! Por favor validar e fechar a issue.
