### ISSUE TITLE
[AWC] bug responsivo

### ISSUE THREAD

**Issue by photonauta35** [photonauta35/institutotim-header-footer#73]
Menu do responsivo está zuado. 

![selecao_124](https://cloud.githubusercontent.com/assets/641411/23030470/069990e8-f455-11e6-92a3-f1807d58273b.png)

**Comment by robertkapa** [comment]
@gusgustavo acho que falhamos em mandar o modelo dos subsites. No model index o responsivo está ok, corrigimos os eventuais erros, mas no index_subdomains está com problemas.

**Comment by robertkapa** [comment]
bug persiste.

**Comment by gusgustavo** [comment]
Ok, alterado. Verifique se resolveu.

**Comment by photonauta35** [comment]
Fechando essa issue pois os itens de layout responsivo estão concentrados em #117
