### ISSUE TITLE
[IT] Botão "English" muda de tamanho ao realizar uma busca

### ISSUE THREAD

**Issue by anatolezano** [photonauta35/institutotim-header-footer#75]

**Comment by anatolezano** [comment]
Home:
![image](https://cloud.githubusercontent.com/assets/25586548/23626229/de701256-028a-11e7-9228-53dbc4567608.png)

Busca:
![image](https://cloud.githubusercontent.com/assets/25586548/23626240/e898875e-028a-11e7-81ec-a561b5be9302.png)

**Comment by anatolezano** [comment]
Ainda não foi resolvido.

**Comment by anatolezano** [comment]
Além disso, na versão em inglês, deveria estar escrito na caixa de busca "Search" ao invés de "O que você procura?".

**Comment by vitor-kato** [comment]
Corrigido
