### ISSUE TITLE
[TFC] Botões redes sociais

### ISSUE THREAD

**Issue by anatolezano** [photonauta35/institutotim-header-footer#77]
Além de não ter os botões de redes sociais no topo, estão faltando os botões que levam aos dois perfis de TFC no Flickr. Além disso, o botão do Facebook no footer está abrindo na mesma página, e deve abrir em uma nova aba.

**Comment by robertkapa** [comment]
@anatolezano quais são os links para essas redes?

**Comment by anatolezano** [comment]
Flickr Fotos: https://www.flickr.com/photos/128197418@N02/albums/
Flickr Atividades: https://www.flickr.com/photos/121406068@N03/albums
YouTube: https://www.youtube.com/channel/UCWnd3qxdHRziiDG_yJfU1hQ

**Comment by anatolezano** [comment]
@robertkapa, já que a Meireles pediu pra retirar os ícones de redes sociais dos projetos, os de TFC não deveriam ser retirados também? Eles ainda estão no header.
