### ISSUE TITLE
[TFC] Problema no botão da busca

### ISSUE THREAD

**Issue by anatolezano** [photonauta35/institutotim-header-footer#79]
O botão da caixa de busca não funciona, só dá para buscar apertando Enter. Além disso, aparece um "x" ao lado da lupa quando começamos a digitar na caixa de busca.

Mesmíssimo problema da issue #85 Colocar igual site do Instituto, igual modelo. 

![selecao_018](https://cloud.githubusercontent.com/assets/641411/25751325/fae0edaa-318a-11e7-91ee-abfbda5cb74c.png)

**Comment by anatolezano** [comment]
![image](https://cloud.githubusercontent.com/assets/25586548/23627436/8267abc2-028f-11e7-9511-7c7786015f6a.png)

**Comment by robertkapa** [comment]
*transformar a lupa em botão*

**Comment by anatolezano** [comment]
Não foi resolvido.

**Comment by anatolezano** [comment]
Ok!
