### ISSUE TITLE
[TFC] Imagem quebrada na página das 7 operações?

### ISSUE THREAD

**Issue by anatolezano** [photonauta35/institutotim-header-footer#80]
Na página das 7 operações (http://timfazciencia.com.br/conheca-as-7-operacoes/), há um ícone de imagem quebrada logo abaixo do header, abaixo da palavra "Pensadores". Não lembro se no site original havia uma imagem nessa página, mas acredito que há sim e que ela não foi carregada. Podem conferir?

**Comment by anatolezano** [comment]
![image](https://cloud.githubusercontent.com/assets/25586548/23627544/faee8a52-028f-11e7-886d-2bed0c1bb39b.png)

**Comment by robertkapa** [comment]
bug persiste. a imagem não existe... 
@anatolezano tem como pedir para a Barbara uma imagem como esta abaixo escrito "as sete operacoes" ? 

![selecao_004](https://cloud.githubusercontent.com/assets/641411/23765129/ec317eb0-04de-11e7-9c03-af93c5122661.png)

**Comment by anatolezano** [comment]
@robertkapa , você ainda tem acesso ao site original? Pode conferir se nessa página tinha ou não uma imagem no topo? Se tiver, vamos ver se conseguimos uma nova. Se não tiver, pode manter sem imagem mesmo, só precisa tirar aquele ícone de imagem quebrada.

**Comment by anatolezano** [comment]
@robertkapa, você pode conferir por gentileza essa questão que eu mencionei há duas semanas sobre esse tópico? Assim poderemos resolvê-lo da melhor forma.

**Comment by gusgustavo** [comment]
Resolvido comentando a linha 28 do arquivo page-conheca.php

**Comment by anatolezano** [comment]
Obrigada! Apenas para confirmar, essa imagem não existia antes no site original, né?
