### ISSUE TITLE
[IT] Rodape: layout quebrado no firefox

### ISSUE THREAD

**Issue by photonauta35** [photonauta35/institutotim-header-footer#81]
Apenas no firefox:

![selecao_002](https://cloud.githubusercontent.com/assets/641411/23762900/53cc6f34-04d6-11e7-8d51-f6e8099e05d2.png)

**Comment by vitor-kato** [comment]
Aqui ta normal

**Comment by anatolezano** [comment]
No meu Firefox, as fontes do header e footer aparecem em Times New Roman.

**Comment by anatolezano** [comment]
Ok!
