### ISSUE TITLE
[TFC] Versão Mobile - link para site

### ISSUE THREAD

**Issue by photonauta35** [photonauta35/institutotim-header-footer#98]
- [ ] Link do logo do projeto deve enviar para home
- [x] Logo do Instituto TIM deve abrir em outra aba e redirecionar para http://institutotim.org.br
![selecao_032](https://cloud.githubusercontent.com/assets/641411/24568672/40b22488-1639-11e7-9e91-02d256efcc6f.png)

**Comment by robertkapa** [comment]
Investiguei o código a primeira vez e não consegui arrumar. A priori está feito corretamente, mas ainda continuava com comportamento errado. 

Dei uma pesquisada e encontrei isso: http://stackoverflow.com/questions/29739561/image-link-is-not-clickable-in-responsive-view

Adicionei um z-index nas classes responsáveis e funcionou para o logo do instituto, mas não para o logo do projeto.

**Comment by photonauta35** [comment]
Essa issue é relativa a comportamento do logo/link, então mesmo que o modelo tenha mudado ela permanece.

**Comment by anatolezano** [comment]
O que isso significa? Dá para corrigir?

**Comment by photonauta35** [comment]
Fechando essa issue porque transferi o conteúdo para essa #116 

https://github.com/photonauta35/institutotim-header-footer/issues/116

**Comment by photonauta35** [comment]
> O que isso significa? Dá para corrigir?

sim.
